target_disk: /dev/sda
efi_partition: /dev/sda1
root_partition: /dev/sda2
chroot_dir: /mnt/debian

debian_suite: sid
debian_mirror: http://deb.debian.org/debian

hostname: base
timezone: Asia/Tokyo
locale: ja_JP.UTF-8

root_password: "root"
