[target]
192.168.77.92 ansible_user=root ansible_password=root ansible_ssh_common_args='-o StrictHostKeyChecking=no' ansible_python_interpreter=/usr/bin/python3
192.168.77.82 ansible_user=root ansible_password=root ansible_ssh_common_args='-o StrictHostKeyChecking=no' ansible_python_interpreter=/usr/bin/python3

[hypervisor]
192.168.77.124 ansible_connection=local ansible_become=true ansible_python_interpreter=/usr/bin/python3
